// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhliuoozfcfoyazeoxbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhobGl1b296ZmNmb3lhemVveGJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2ODEyMzYsImV4cCI6MjA2NzI1NzIzNn0.1ZRNSlz5HHxFgfyWdH2htxPJOwPGcsumkfQZiFlhGXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});